# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3baa0e797b97d6d5b93f67e6c4fd582b"
name = "compliance_copilot_app"
handle = "compliance-copilot-app"
application_url = "https://earn-tribune-preliminary-rolled.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "/webhooks/customers/data_collection"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/updated" ]
  uri = "/webhooks/orders/data_collection"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create", "checkouts/update" ]
  uri = "/webhooks/checkouts/data_collection"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_checkouts,read_content,read_customers,read_orders,read_products,read_script_tags,read_themes,write_script_tags"

[auth]
redirect_urls = ["https://earn-tribune-preliminary-rolled.trycloudflare.com/auth/callback", "https://earn-tribune-preliminary-rolled.trycloudflare.com/auth/shopify/callback", "https://earn-tribune-preliminary-rolled.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
